version: '3.7'

services:

  idea-test:
    container_name: idea-test
    build: .
    ports:
      - "5457:5457"

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "13306:3306"
    volumes:
      - ${PWD}/migrations:/docker-entrypoint-initdb.d

